# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Iowa City SURJ
description: > # this means to ignore newlines until "baseurl:"

facebook-url: https://www.facebook.com/ICSURJ/
twitter-url: https://twitter.com/icsurj
email: icsurj@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://icsurj.org" # the base hostname & protocol for your site
permalink: /news/:year/:title/

collections:
    - local-organizations

# Build settings
markdown: kramdown
timezone: America/Central
